modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/NovaMachina-Mods/ExNihiloJEI/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="exnjei"
    logoFile="exnjei.png"
    version="1.0.0"
    displayName="Ex Nihilo: Sequentia - JEI Addon"
    updateJSONURL="https://api.modrinth.com/updates/000000/forge_updates.json"
    authors="NovaMachina"
    description='''Adds support for JEI to Ex Nihilo: Sequentia'''

[[dependencies.exnjei]]
    modId="neoforge"
    type="required"
    versionRange="[20.4, 21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnjei]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnjei]]
   modId="exnihilosequentia"
   type="required"
   ordering="AFTER"
   side="BOTH"
   versionRange="[6.0.0, 6.1.0)"

[[dependencies.exnjei]]
   modId="jei"
   type="required"
   ordering="AFTER"
   side="BOTH"
   versionRange="[17.3.0.0, 17.3.1.0)"

